dict set ::params N_STREAMS 7
dict set ::params M_MACROS 64
dict set ::params DATA_WIDTH 32
dict set ::params ADDR_WIDTH 32
dict set ::params MACRO_DEPTH 512
dict set ::params B_BANKS 8
dict set ::params DEPTH 8
dict set ::params NUM_REQS 4
dict set ::params W_WORKERS 8
dict set ::params FIFO_DEPTH 8
dict set ::params STRIDE_WIDTH 14
dict set ::params COUNT_WIDTH 10
dict set ::params NUM_AXES 4
dict set ::params STREAM_OFFSET_WIDTH 20
dict set ::params BANK_DEPTH 16384